# Generated by Django 5.1.6 on 2025-02-26 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table='tbl_tasks',
        ),
    ]
