# Generated by Django 5.1.6 on 2025-02-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que la tarea fue creada.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción detallada de la tarea (opcional).', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'Por Hacer'), ('IN_PROGRESS', 'En Progreso'), ('DONE', 'Hecho')], default='TO_DO', help_text='Estado actual de la tarea. Valores posibles: TO_DO, IN_PROGRESS, DONE.', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.AutoField(help_text='Identificador único de la tarea.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='Título de la tarea. Debe ser descriptivo y claro.', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización de la tarea.'),
        ),
    ]
